# Generated by Django 5.2 on 2025-04-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(),
        ),
    ]
